/* tslint:disable */
/* eslint-disable */
/**
 * Elysia Documentation
 * Development documentation
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface GetAnalytics200Response
 */
export interface GetAnalytics200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetAnalytics200Response
     */
    'success': boolean;
}
/**
 * 
 * @export
 * @interface GetChatGetMessages200Response
 */
export interface GetChatGetMessages200Response {
    /**
     * 
     * @type {Array<GetChatGetMessages200ResponseMessagesInner>}
     * @memberof GetChatGetMessages200Response
     */
    'messages': Array<GetChatGetMessages200ResponseMessagesInner>;
    /**
     * 
     * @type {GetChatGetMessages200ResponsePagination}
     * @memberof GetChatGetMessages200Response
     */
    'pagination': GetChatGetMessages200ResponsePagination;
}
/**
 * 
 * @export
 * @interface GetChatGetMessages200ResponseMessagesInner
 */
export interface GetChatGetMessages200ResponseMessagesInner {
    /**
     * 
     * @type {string}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'imageUrl': string | null;
    /**
     * 
     * @type {string}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'imageHash': string | null;
    /**
     * 
     * @type {GetChatGetMessages200ResponseMessagesInnerCreatedAt}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'createdAt': GetChatGetMessages200ResponseMessagesInnerCreatedAt;
    /**
     * 
     * @type {GetChatGetMessages200ResponseMessagesInnerType}
     * @memberof GetChatGetMessages200ResponseMessagesInner
     */
    'type': GetChatGetMessages200ResponseMessagesInnerType;
}
/**
 * 
 * @export
 * @interface GetChatGetMessages200ResponseMessagesInnerCreatedAt
 */
export interface GetChatGetMessages200ResponseMessagesInnerCreatedAt {
}
/**
 * 
 * @export
 * @interface GetChatGetMessages200ResponseMessagesInnerType
 */
export interface GetChatGetMessages200ResponseMessagesInnerType {
}
/**
 * 
 * @export
 * @interface GetChatGetMessages200ResponsePagination
 */
export interface GetChatGetMessages200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof GetChatGetMessages200ResponsePagination
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof GetChatGetMessages200ResponsePagination
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof GetChatGetMessages200ResponsePagination
     */
    'totalMessages': number;
    /**
     * 
     * @type {number}
     * @memberof GetChatGetMessages200ResponsePagination
     */
    'totalPages': number;
}
/**
 * 
 * @export
 * @interface GetUserMe200Response
 */
export interface GetUserMe200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetUserMe200Response
     */
    'hasFreeRequests': boolean;
}
/**
 * 
 * @export
 * @interface PostChatSendMessage200Response
 */
export interface PostChatSendMessage200Response {
    /**
     * 
     * @type {GetChatGetMessages200ResponseMessagesInner}
     * @memberof PostChatSendMessage200Response
     */
    'message': GetChatGetMessages200ResponseMessagesInner;
}
/**
 * 
 * @export
 * @interface PostChatSendMessageRequest
 */
export interface PostChatSendMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof PostChatSendMessageRequest
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof PostChatSendMessageRequest
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostChatSendMessageRequest
     */
    'imageHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostChatSendMessageRequest
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof PostChatSendMessageRequest
     */
    'locale': string;
}
/**
 * 
 * @export
 * @interface PostUserCheckSubscription200Response
 */
export interface PostUserCheckSubscription200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostUserCheckSubscription200Response
     */
    'isActive': boolean;
}
/**
 * 
 * @export
 * @interface PostUserLoginRequest
 */
export interface PostUserLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserLoginRequest
     */
    'appUserId': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserLoginRequest
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserLoginRequest
     */
    'identityToken': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserLoginRequest
     */
    'fcmToken': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserLoginRequest
     */
    'locale': string;
    /**
     * 
     * @type {string}
     * @memberof PostUserLoginRequest
     */
    'email'?: string;
}
/**
 * 
 * @export
 * @interface PostUserUpdateLocaleRequest
 */
export interface PostUserUpdateLocaleRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserUpdateLocaleRequest
     */
    'locale': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAnalytics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/analytics/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChatGetMessages: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/chat/getMessages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postAnalyticsLaunch: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('postAnalyticsLaunch', 'body', body)
            const localVarPath = `/analytics/launch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PostChatSendMessageRequest} postChatSendMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postChatSendMessage: async (postChatSendMessageRequest: PostChatSendMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postChatSendMessageRequest' is not null or undefined
            assertParamExists('postChatSendMessage', 'postChatSendMessageRequest', postChatSendMessageRequest)
            const localVarPath = `/chat/sendMessage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postChatSendMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postHooksRevenueCat: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/hooks/revenue-cat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserCheckSubscription: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/check-subscription`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserDeleteAccount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/delete-account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PostUserLoginRequest} postUserLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserLogin: async (postUserLoginRequest: PostUserLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postUserLoginRequest' is not null or undefined
            assertParamExists('postUserLogin', 'postUserLoginRequest', postUserLoginRequest)
            const localVarPath = `/user/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUserLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PostUserUpdateLocaleRequest} postUserUpdateLocaleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserUpdateLocale: async (postUserUpdateLocaleRequest: PostUserUpdateLocaleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postUserUpdateLocaleRequest' is not null or undefined
            assertParamExists('postUserUpdateLocale', 'postUserUpdateLocaleRequest', postUserUpdateLocaleRequest)
            const localVarPath = `/user/update-locale`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUserUpdateLocaleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAnalytics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAnalytics200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAnalytics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAnalytics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getChatGetMessages(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetChatGetMessages200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getChatGetMessages(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getChatGetMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserMe200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUserMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postAnalyticsLaunch(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAnalytics200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postAnalyticsLaunch(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postAnalyticsLaunch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PostChatSendMessageRequest} postChatSendMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postChatSendMessage(postChatSendMessageRequest: PostChatSendMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostChatSendMessage200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postChatSendMessage(postChatSendMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postChatSendMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postHooksRevenueCat(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postHooksRevenueCat(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postHooksRevenueCat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserCheckSubscription(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostUserCheckSubscription200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUserCheckSubscription(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postUserCheckSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserDeleteAccount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUserDeleteAccount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postUserDeleteAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PostUserLoginRequest} postUserLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserLogin(postUserLoginRequest: PostUserLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUserLogin(postUserLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postUserLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PostUserUpdateLocaleRequest} postUserUpdateLocaleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUserUpdateLocale(postUserUpdateLocaleRequest: PostUserUpdateLocaleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUserUpdateLocale(postUserUpdateLocaleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postUserUpdateLocale']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAnalytics(options?: RawAxiosRequestConfig): AxiosPromise<GetAnalytics200Response> {
            return localVarFp.getAnalytics(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getChatGetMessages(page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetChatGetMessages200Response> {
            return localVarFp.getChatGetMessages(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserMe(options?: RawAxiosRequestConfig): AxiosPromise<GetUserMe200Response> {
            return localVarFp.getUserMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postAnalyticsLaunch(body: object, options?: RawAxiosRequestConfig): AxiosPromise<GetAnalytics200Response> {
            return localVarFp.postAnalyticsLaunch(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PostChatSendMessageRequest} postChatSendMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postChatSendMessage(postChatSendMessageRequest: PostChatSendMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<PostChatSendMessage200Response> {
            return localVarFp.postChatSendMessage(postChatSendMessageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postHooksRevenueCat(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postHooksRevenueCat(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserCheckSubscription(options?: RawAxiosRequestConfig): AxiosPromise<PostUserCheckSubscription200Response> {
            return localVarFp.postUserCheckSubscription(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserDeleteAccount(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postUserDeleteAccount(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PostUserLoginRequest} postUserLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserLogin(postUserLoginRequest: PostUserLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postUserLogin(postUserLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PostUserUpdateLocaleRequest} postUserUpdateLocaleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUserUpdateLocale(postUserUpdateLocaleRequest: PostUserUpdateLocaleRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postUserUpdateLocale(postUserUpdateLocaleRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAnalytics(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAnalytics(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getChatGetMessages(page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getChatGetMessages(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserMe(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postAnalyticsLaunch(body: object, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postAnalyticsLaunch(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostChatSendMessageRequest} postChatSendMessageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postChatSendMessage(postChatSendMessageRequest: PostChatSendMessageRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postChatSendMessage(postChatSendMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postHooksRevenueCat(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postHooksRevenueCat(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUserCheckSubscription(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUserCheckSubscription(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUserDeleteAccount(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUserDeleteAccount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostUserLoginRequest} postUserLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUserLogin(postUserLoginRequest: PostUserLoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUserLogin(postUserLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PostUserUpdateLocaleRequest} postUserUpdateLocaleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postUserUpdateLocale(postUserUpdateLocaleRequest: PostUserUpdateLocaleRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postUserUpdateLocale(postUserUpdateLocaleRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



